# running htop for host system from container. 

# docker run --rm --name htop -it \
# --pid host \
# omegazyadav/htop



FROM alpine:latest

MAINTAINER "Yadav Lamichhane <omegazyadav1@gmail.com> "

RUN apk add --update htop  


CMD ["htop"]


