name: Pipeline for dockerfiles
on:
  push:
    branches: [ github-ci ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2 
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKERHUB_REG }} --password-stdin

        - name: Get the docker tag
          id: vars
          run: echo ::set-output name=tag::$(echo $(git log -n1 --date=format:'%y%m%d-' --format=%cd%h))
        
        - name: Build htop
          run: docker build $PWD/htop --file htop/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/htop:${{ steps.vars.outputs.tag }}
        - name: Push htop
          run: docker push ${{ secrets.DOCKERHUB_USER }}/htop:${{ steps.vars.outputs.tag }}

        - name: Build netstat 
          run: docker build $PWD/netstat --file netstat/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/netstat:${{ steps.vars.outputs.tag }}
        - name: Push netstat
          run: docker push ${{ secrets.DOCKERHUB_USER }}/netstat:${{ steps.vars.outputs.tag }}
