name: Pipeline for dockerfiles
on:
  push:
    branches: [ github-ci ]
  pull_request:
    branches: [ main ]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2 
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_USER }} ${{ secrets.DOCKERHUB_REG }} --password-stdin

        - name: Get the docker tag
          id: vars
          run: echo ::set-output name=tag::$(echo $(git log -n1 --date=format:'%y%m%d-' --format=%cd%h))
        
        - name: Build htop
          run: docker build $PWD/htop --file htop/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/htop:${{ steps.vars.outputs.tag }}
        - name: Push htop
          run: docker push ${{ secrets.DOCKERHUB_USER }}/htop:${{ steps.vars.outputs.tag }}

        - name: Build netstat 
          run: docker build $PWD/netstat --file netstat/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/netstat:${{ steps.vars.outputs.tag }}
        - name: Push netstat
          run: docker push ${{ secrets.DOCKERHUB_USER }}/netstat:${{ steps.vars.outputs.tag }}

  github-registry:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Authentication with github container registry
          run: echo ${{ secrets.GH_TOKEN }} | docker login docker.pkg.github.com -u omegazyadav --password-stdin
        - name: Get the docker tag
          id: vars
          run: echo ::set-output name=tag::$(echo $(git log -n1 --date=format:'%y%m%d-' --format=%cd%h))
        - name: Build htop
          run: docker build $PWD/htop --file htop/Dockerfile --tag htop
        - name: Tag htop
          run: docker tag htop:latest docker.pkg.github.com/omegazyadav/dockerfiles/htop:${{ steps.vars.outputs.tag }}
        - name: Push htop
          run: docker push docker.pkg.github.com/omegazyadav/dockerfles/htop:${{ steps.vars.outputs.tag }}
